---
- name: loops
  hosts: all
  become: yes
  tasks:
    - name: this will install
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - wget
        - curl
        - nginx
