---
- name: tag
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: service
      service:
        name: apache2
        state: started
      ignore_errors: yes
      tags: test-team
    - name: install java
      apt:
        name: default-jre
        state: present
      ignore_errors: yes
      tags: dev-team

