---
- name: test
  hosts: webservers
  become: yes
  vars:
    name: bharath
    number: 12345
  tasks:
    - name: it will install apache2
      apt:
        name: apache2 
        state: present
    - name: it will start up the server
      service:
        name: apache2
        state: started
    - name: it will copy index.html to target servers
      template:
        src: /home/ansible/ansible/index.html 
        dest: /var/www/html/index.html
      notify:
        - restart the web server 
  handlers:
    - name: this will restart test-apache2
      service:
        name: apache2 
        state: restarted
        enabled: true
