---
- name: testing with vars
  hosts: all
  become: yes
  vars:
    pkg:
      - wget
      - tree
      - nginx
  tasks:
    - name: it will install pkgs one by one
      apt:
        name: "{{ pkg }}"
        update_cache: yes
        state: present
